apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: preview-ingress
spec:
  ingressClassName: REPLACE_INGRESS_CLASS
  rules:
  - host: preview.local
    http:
      paths:
      - path: /echo
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80
