apiVersion: v1
kind: PersistentVolume
metadata:
  name: preview-retained-pv
spec:
  capacity:
    storage: 250Mi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: ''
  local:
    path: /var/tmp/cloud-lab-preview-data
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - REPLACE_WORKER_HOSTNAME
