apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: data
  namespace: preview-class
spec:
  storageClassName: preview-delayed
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 250Mi
