apiVersion: v1
kind: Namespace
metadata:
  name: lab-self-storage
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: lab-self-local
provisioner: rancher.io/local-path
reclaimPolicy: Delete
volumeBindingMode: WaitForFirstConsumer
---
apiVersion: v1
kind: Service
metadata:
  name: data
  namespace: lab-self-storage
spec:
  selector:
    app: data
  ports:
  - port: 80
    targetPort: 80
  clusterIP: None
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data
  namespace: lab-self-storage
spec:
  selector:
    matchLabels:
      app: data
  template:
    metadata:
      labels:
        app: data
    spec:
      containers:
      - name: web
        image: nginx:1.28-alpine
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 64Mi
        volumeMounts:
        - name: disk
          mountPath: /data
  replicas: 2
  serviceName: data
  volumeClaimTemplates:
  - metadata:
      name: disk
    spec:
      accessModes:
      - ReadWriteOnce
      storageClassName: lab-self-local
      resources:
        requests:
          storage: 64Mi
