apiVersion: v1
kind: Namespace
metadata:
  name: lab-self-edge
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  namespace: lab-self-edge
spec:
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: web
        image: nginx:1.28-alpine
        resources:
          requests:
            cpu: 10m
            memory: 16Mi
          limits:
            cpu: 100m
            memory: 64Mi
  replicas: 1
---
apiVersion: v1
kind: Service
metadata:
  name: web
  namespace: lab-self-edge
spec:
  selector:
    app: web
  ports:
  - port: 80
    targetPort: 80
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web
  namespace: lab-self-edge
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  ingressClassName: lab-traefik
  rules:
  - host: study.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80
