apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: web-tls
  namespace: lab-self-edge
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: websecure
spec:
  ingressClassName: lab-traefik
  rules:
  - host: study.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: web
            port:
              number: 80
  tls:
  - hosts:
    - study.local
    secretName: web-tls
