apiVersion: v1
kind: LimitRange
metadata:
  name: defaults
  namespace: lab-self-placement
spec:
  limits:
  - type: Container
    default:
      cpu: 200m
      memory: 64Mi
    defaultRequest:
      cpu: 50m
      memory: 32Mi
    max:
      cpu: 300m
      memory: 128Mi
