apiVersion: v1
kind: Pod
metadata:
  name: over
  namespace: lab-self-placement
spec:
  restartPolicy: Never
  containers:
  - name: app
    image: busybox:1.37
    command:
    - sleep
    - '3600'
    resources:
      requests:
        cpu: 400m
        memory: 32Mi
      limits:
        cpu: 400m
        memory: 64Mi
