apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: too-broad
  namespace: preview-backend
spec:
  podSelector: {}
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector: {}
