apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: wrong-label
  namespace: preview-backend
spec:
  podSelector:
    matchLabels:
      app: database
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          kubernetes.io/metadata.name: preview-frontend
      podSelector:
        matchLabels:
          app: frontend
